### ISSUE TITLE
Error when creating a Tracking with AES authentication type

### ISSUE THREAD

**Issue by clementamat** [AfterShip/tracking-sdk-nodejs#13]
I'm facing an issue when trying to create a tracking with the SDK when I'm using the AES authentication type.

### Steps to Reproduce

Basically using the Getting started code snippet for creating a tracking with the SDK. The only custom parameter is the authentication type as I'm using AES instead of API_KEY here.

The following example works properly when using the API_KEY auth_type

```javascript
const {AfterShip} = require('@aftership/tracking-sdk');


// Step 2: Initialize the client object
const aftership = new AfterShip(
    {
        api_key: 'my_api_key',
        api_secrect: 'my_secret',
        auth_type: 'AES',
        max_retry: 3,
    }
);

// Step 3: Create the request object
const createTrackingRequestBody = {
    tracking_number: 'my_tracking_number',
    slug: 'tnt'
};

// Step 4: Make the request
aftership.tracking.createTracking(createTrackingRequestBody)
    .then(tracking => console.log(tracking))
    .catch(error => console.log(error));
```

### Expected Behavior
I should be able to create my tracking

### Actual Behavior
I end up with an error catched in my catch block : 

```javascript
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at Hash.update (node:internal/crypto/hash:115:11)
    at Authentication.signMessage (/Users/clement/Lab/test-aftership/node_modules/@aftership/tracking-sdk/dist/lib/authentication.js:53:28)
    at Authentication.sign (/Users/clement/Lab/test-aftership/node_modules/@aftership/tracking-sdk/dist/lib/authentication.js:19:35)
    at Request.getHeaders (/Users/clement/Lab/test-aftership/node_modules/@aftership/tracking-sdk/dist/lib/request.js:41:68)
    at Request.<anonymous> (/Users/clement/Lab/test-aftership/node_modules/@aftership/tracking-sdk/dist/lib/request.js:110:34)
    at Generator.next (<anonymous>)
    at /Users/clement/Lab/test-aftership/node_modules/@aftership/tracking-sdk/dist/lib/request.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/clement/Lab/test-aftership/node_modules/@aftership/tracking-sdk/dist/lib/request.js:4:12)
    at Request.makeRequest (/Users/clement/Lab/test-aftership/node_modules/@aftership/tracking-sdk/dist/lib/request.js:109:16) {
  code: 'ERR_INVALID_ARG_TYPE'
```

### SDK Version
"@aftership/tracking-sdk": "^10.0.1"

### Environment Details

- **Node.js Version**: v20.17.0
- **Package Manager**: yarn

**Comment by 1415003719** [comment]
fixed
